name: Build and Deploy API
on: 
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Build and Deploy Grider Worker
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker container image
      run: docker build ./apps/worker -f ./apps/worker/Dockerfile -t techhead/grider-worker:latest
      
    - name: Push the image to hub.docker.com
      run: |
        docker login -u techhead -p "${DOCKER_HUB_PASS}"
        docker push techhead/grider-worker:latest
      env:
        DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
