name: Build and Deploy Grider Client
on: 
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Build Grider Client
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker container image
      run: docker build ./apps/client -f ./apps/client/Dockerfile -t techhead/grider-client:latest
      
    - name: Push the image to hub.docker.com
      run: |
        docker login -u techhead -p "${DOCKER_HUB_PASS}"
        docker push techhead/grider-client:latest
      env:
        DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
